### ISSUE TITLE
[FEAT] 마이 페이지 UI 구현

### ISSUE THREAD

**Issue by phonil** [MyIceCreamBox/IceCreamBox-Front#10]
## Description
마이 페이지 구현

## Todo
- [x] 마이 페이지 UI
- [x] 아이스크림 확인 UI
- [x] 아이스크림 상세 보기 UI

## etc
화면 비율 문제로 stick bar 대신 chart 사용
아이스크림 상세 보기 - 모달
