### ISSUE TITLE
[FEAT] 로그인 후 메인 API 연결

### ISSUE THREAD

**Issue by yuraup** [MyIceCreamBox/IceCreamBox-Front#15]
## Description
로그인 후 메인페이지 API 및 추가 기능 

## Todo
- [x] 받은 선물 확인 API 연결
- [x] 보낼 수 있는 기회 API 연결
- [x] 링크 공유 API 연결

## etc
해당사항 없음
