### ISSUE TITLE
[FEAT]User API 연결

### ISSUE THREAD

**Issue by seuriseuljjeok** [MyIceCreamBox/IceCreamBox-Front#16]
## Description
작업 내용을 입력해주세요

## Todo
- [x] 로그인 API 연결
- [x] 회원가입 API 연결
- [x] 닉네임 확인 API 연결
- [x] 이메일 확인 API 연결
- [x] 로그아웃
## etc
해당사항 없음
