### ISSUE TITLE
[FEAT] 마이 페이지 API 연결

### ISSUE THREAD

**Issue by phonil** [MyIceCreamBox/IceCreamBox-Front#22]
## Description
마이페이지 API 및 추가 기능 

## Todo
- [x] 받은 아이스크림 목록 API 연결 (전체 아이스크림)
      - chart
- [x] 받은 아이스크림 API 연결  (아이스크림 각각)
      - 보낸 사람 닉네임
      - message
- [x] 마이페이지 API 연결
- [x] 아이스크림 확인 기간 API 연결

## etc
해당사항 없음
