### ISSUE TITLE
[FEAT] 404 에러 연결

### ISSUE THREAD

**Issue by seuriseuljjeok** [MyIceCreamBox/IceCreamBox-Front#33]
## Description
404 에러 연결

## Todo
- [x] 마이페이지
- [x] 링크공유
- [x] 선물보내기
- [x] 받은 선물개수 확인
- [x] 보낼 수 있는 기회 확인
- [x] 선물 아이스크림 비율 확인

## etc
해당사항 없음
