### ISSUE TITLE
[FEAT] sendpage UI/기능/ api 연결

### ISSUE THREAD

**Issue by root-51** [MyIceCreamBox/IceCreamBox-Front#38]
## UI 개발
아이스크림보내기와 관련된 페이지의 UI 개발
 - selectIcecream 페이지
 - writeLetter 페이지 
 - configLetter 페이지
 - finishSend 페이지 
## 기능 구현 
 - 아이스크림 선택, 편지 작성, 편지 보내기 기능 구현
### 세부 기능 구현
1. selectIcecream
 - 아이스크림 중복 선택 안되게 처리 
 - 받는 사람 입력 또는 아이스크림 선택을 안 하면 다음 화면(writeLetter)으로 못 넘어가게 처리
2. writeLetter 
 - 보내는 사람 또는 편지를 입력하지 않으면 다음 화면(configLetter)으로 못 넘어가게 처리
3. configLetter
 - 받는 사람이 가입된 사람 중 없는 경우 에러 처리, 보내기 취소
## API연결
 - configLetter에서 보내기 버튼을 눌렀을 때 작성한 편지와 아이스크림을 POST
## Todo
- [x] selectIcecream UI 및 기능
- [x] writeLetter UI 및 기능
- [x] configLetter UI 및 기능
- [x] finishSend UI 및 기능
- [x] API 연결

## etc
해당사항 없음
